module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'build',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'user',
        'role',
        'permission',
        'token',
        'session',
        'oauth',
        'mfa',
        'audit',
        'security',
        'db',
        'api',
        'test',
        'ci',
        'docs',
        'config',
        'deps',
      ],
    ],
    'subject-case': [2, 'always', 'sentence-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'body-max-line-length': [2, 'always', 100],
    'footer-max-line-length': [2, 'always', 100],
  },
};
