apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msseguridad.fullname" . }}-config
  labels:
    {{- include "msseguridad.labels" . | nindent 4 }}
data:
  # Application configuration
  NODE_ENV: {{ .Values.env | default "production" | quote }}
  PORT: "3000"
  # Add other non-sensitive config here
